-- Initialize databases for NocoDB and Metabase
CREATE DATABASE nocodb;
CREATE USER nocodb WITH PASSWORD 'nocodb';
GRANT ALL PRIVILEGES ON DATABASE nocodb TO nocodb;

CREATE DATABASE metabase;
CREATE USER metabase WITH PASSWORD 'metabase';
GRANT ALL PRIVILEGES ON DATABASE metabase TO metabase;

-- Grant schema permissions for NocoDB
\c nocodb
GRANT ALL ON SCHEMA public TO nocodb;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO nocodb;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO nocodb;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO nocodb;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO nocodb;

-- Grant schema permissions for Metabase
\c metabase
GRANT ALL ON SCHEMA public TO metabase;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO metabase;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO metabase;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO metabase;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO metabase;
